In [1]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

import pandas as pd
pd.set_option("display.max_columns",30)
import requests

In [2]:
current_datetime = datetime.now() - relativedelta(month=2)
formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = (

    f"https://data.cityofchicago.org/resource/ajtu-isnz.json?"
    f"$where=trip_start_timestamp >= '{formatted_datetime}T00:00:00' "
    f"AND trip_start_timestamp <= '{formatted_datetime}T23:59:59' "
    f"&$limit=30000"
)

response = requests.get(url)
data = response.json()

len(data)

12118

In [3]:
taxi_trips = pd.DataFrame(data)

#taxi_trips.head()

In [4]:
taxi_trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 12118 entries, 0 to 12117
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     12118 non-null  str
 1   taxi_id                     12118 non-null  str
 2   trip_start_timestamp        12118 non-null  str
 3   trip_end_timestamp          12117 non-null  str
 4   trip_seconds                12116 non-null  str
 5   trip_miles                  12118 non-null  str
 6   pickup_community_area       11769 non-null  str
 7   dropoff_community_area      10803 non-null  str
 8   fare                        12098 non-null  str
 9   tips                        12098 non-null  str
 10  tolls                       12098 non-null  str
 11  extras                      12098 non-null  str
 12  trip_total                  12098 non-null  str
 13  payment_type                12118 non-null  str
 14  company                     12118 non-null  str
 15  pickup_centroid_latitude    11772 non-null  str
 16  pickup_centroid_longitude   11772 non-null  str
 17  pickup_centroid_location    11772 non-null  object
 18  dropoff_centroid_latitude   10847 non-null  str
 19  dropoff_centroid_longitude  10847 non-null  str
 20  dropoff_centroid_location   10847 non-null  object
 21  pickup_census_tract         3935 non-null   str
 22  dropoff_census_tract        3727 non-null   str
dtypes: object(2), str(21)
memory usage: 2.1+ MB

In [5]:
taxi_trips.describe()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
count,12118,12118,12118,12117,12116,12118,11769,10803,12098,12098,12098,12098,12098,12118,12118,11772,11772,11772,10847,10847,10847,3935,3727
unique,12118,2003,96,104,2957,2180,77,77,1539,898,23,178,2464,7,31,127,127,127,145,145,145,50,71
top,e5d9a80c893b13e39f3fffa499adcea74e19cc38,32aa143752e0ab419df8db4d44e341571c4cad6ddd1515...,2026-02-16T14:15:00.000,2026-02-16T12:00:00.000,0,0,76,8,8.5,0,0,0,3.25,Credit Card,Flash Cab,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",17031980000,17031839100
freq,1,37,238,241,140,827,3451,2923,276,6496,11958,7802,161,4625,2727,2164,2164,2164,1485,1485,1485,1287,522

In [6]:
taxi_trips[taxi_trips["fare"].isna()].sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
9795,8443525030aca98b09bc6e30934c29fb84c0ebfd,2407ff99e367ceb469a8cc6663e6ad6ec51fb0f401d370...,2026-02-16T09:30:00.000,2026-02-16T10:00:00.000,2123,18.32,76,32,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.884987192,-87.620992913,"{'type': 'Point', 'coordinates': [-87.62099291...",17031980000,17031320100
5729,1a060fa94016659fe8270435638b5a6845fcf52d,b7ac477e614f1f222f42c698e3f2841fb020060e629172...,2026-02-16T14:45:00.000,2026-02-16T15:30:00.000,2348,16.5,76,8,NaN,NaN,NaN,NaN,NaN,Cash,Taxicab Insurance Agency Llc,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.892507781,-87.626214906,"{'type': 'Point', 'coordinates': [-87.62621490...",17031980000,17031081500
7354,bb64fac08d2f1aa3db6a53c615070a947180113e,87a21e5ac34dbe38d564b74375f29cdcc5f88e81aa27d9...,2026-02-16T12:45:00.000,2026-02-16T12:45:00.000,719,4.65,6,77,NaN,NaN,NaN,NaN,NaN,Cash,Flash Cab,41.944226601,-87.655998182,"{'type': 'Point', 'coordinates': [-87.65599818...",41.9867118,-87.663416405,"{'type': 'Point', 'coordinates': [-87.66341640...",NaN,NaN
4744,e436a006ee6053d4842721405ff38c774523b95d,972dd37a560c48d4253f1773a6f98245d83a075192605a...,2026-02-16T15:45:00.000,2026-02-16T16:30:00.000,2787,12,76,2,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",42.001571027,-87.695012589,"{'type': 'Point', 'coordinates': [-87.69501258...",NaN,NaN
3867,4ad48ac5270ea5439fb5439601d8555f7de55657,4b92a02bf38d961c406e957edbe057dcafbd12d849d136...,2026-02-16T17:00:00.000,2026-02-16T17:45:00.000,2852,16.71,76,8,NaN,NaN,NaN,NaN,NaN,Cash,City Service,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.892507781,-87.626214906,"{'type': 'Point', 'coordinates': [-87.62621490...",17031980000,17031081500

### Transformaion: deal with NaN values

In [7]:
taxi_trips.drop(["pickup_census_tract","dropoff_census_tract"],axis=1,inplace=True)

taxi_trips.drop(["pickup_centroid_location","dropoff_centroid_location"],axis=1,inplace=True)

In [8]:
taxi_trips.dropna(inplace=True)

In [9]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 10661 entries, 0 to 12116
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     10661 non-null  str
 1   taxi_id                     10661 non-null  str
 2   trip_start_timestamp        10661 non-null  str
 3   trip_end_timestamp          10661 non-null  str
 4   trip_seconds                10661 non-null  str
 5   trip_miles                  10661 non-null  str
 6   pickup_community_area       10661 non-null  str
 7   dropoff_community_area      10661 non-null  str
 8   fare                        10661 non-null  str
 9   tips                        10661 non-null  str
 10  tolls                       10661 non-null  str
 11  extras                      10661 non-null  str
 12  trip_total                  10661 non-null  str
 13  payment_type                10661 non-null  str
 14  company                     10661 non-null  str
 15  pickup_centroid_latitude    10661 non-null  str
 16  pickup_centroid_longitude   10661 non-null  str
 17  dropoff_centroid_latitude   10661 non-null  str
 18  dropoff_centroid_longitude  10661 non-null  str
dtypes: str(19)
memory usage: 1.6 MB

### Transformation: renaming

In [10]:
taxi_trips.rename(columns= { "pickup_community_area" : "pickup_community_area_id", 
                           "dropoff_community_area" : "dropoff_community_area_id"
                           }, inplace=True)

In [11]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id',
       'dropoff_community_area_id', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude'],
      dtype='str')

### Transformation:create helper column for weather and date dimension

In [12]:
taxi_trips["trip_start_timestamp"] = pd.to_datetime(taxi_trips["trip_start_timestamp"])

In [13]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 10661 entries, 0 to 12116
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     10661 non-null  str
 1   taxi_id                     10661 non-null  str
 2   trip_start_timestamp        10661 non-null  datetime64[us]
 3   trip_end_timestamp          10661 non-null  str
 4   trip_seconds                10661 non-null  str
 5   trip_miles                  10661 non-null  str
 6   pickup_community_area_id    10661 non-null  str
 7   dropoff_community_area_id   10661 non-null  str
 8   fare                        10661 non-null  str
 9   tips                        10661 non-null  str
 10  tolls                       10661 non-null  str
 11  extras                      10661 non-null  str
 12  trip_total                  10661 non-null  str
 13  payment_type                10661 non-null  str
 14  company                     10661 non-null  str
 15  pickup_centroid_latitude    10661 non-null  str
 16  pickup_centroid_longitude   10661 non-null  str
 17  dropoff_centroid_latitude   10661 non-null  str
 18  dropoff_centroid_longitude  10661 non-null  str
dtypes: datetime64[us](1), str(18)
memory usage: 1.6 MB

In [14]:
taxi_trips["datetime_for_weather"] = taxi_trips["trip_start_timestamp"].dt.floor("h")

In [15]:
taxi_trips["datetime_for_weather"].unique()

<DatetimeArray>
['2026-02-16 23:00:00', '2026-02-16 22:00:00', '2026-02-16 21:00:00',
 '2026-02-16 20:00:00', '2026-02-16 19:00:00', '2026-02-16 18:00:00',
 '2026-02-16 17:00:00', '2026-02-16 16:00:00', '2026-02-16 15:00:00',
 '2026-02-16 14:00:00', '2026-02-16 13:00:00', '2026-02-16 12:00:00',
 '2026-02-16 11:00:00', '2026-02-16 10:00:00', '2026-02-16 09:00:00',
 '2026-02-16 08:00:00', '2026-02-16 07:00:00', '2026-02-16 06:00:00',
 '2026-02-16 05:00:00', '2026-02-16 04:00:00', '2026-02-16 03:00:00',
 '2026-02-16 02:00:00', '2026-02-16 01:00:00', '2026-02-16 00:00:00']
Length: 24, dtype: datetime64[us]

In [16]:
taxi_trips["trip_start_date"] = pd.to_datetime(taxi_trips["trip_start_timestamp"]).dt.date

In [17]:
taxi_trips["trip_start_date"].sample(5)

7403     2026-02-16
6453     2026-02-16
10236    2026-02-16
458      2026-02-16
600      2026-02-16
Name: trip_start_date, dtype: object

 ### check: join taxi and weather data

In [18]:
current_datetime = datetime.now() - relativedelta(month=2)
formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = ("https://archive-api.open-meteo.com/v1/era5")


params = {
    "latitude": 41.85,
    "longitude": -87.65,
    "start_date": formatted_datetime,
    "end_date": formatted_datetime,
    "hourly":"temperature_2m,wind_speed_10m,rain,precipitation"

}

response = requests.get(url, params = params)
data = response.json()

weather_data = {
    "datetime": data["hourly"]["time"],
    "temperature": data["hourly"]["temperature_2m"],
    "wind_speed": data["hourly"]["wind_speed_10m"],
    "rain": data["hourly"]["rain"],
    "precipitation": data["hourly"]["precipitation"],
}

weather_df = pd.DataFrame(weather_data)

weather_df["datetime"] = pd.to_datetime(weather_df["datetime"])

weather_df.head()

             datetime  temperature  wind_speed  rain  precipitation
0 2026-02-16 00:00:00          9.4         3.0   0.0            0.0
1 2026-02-16 01:00:00          8.4         3.5   0.0            0.0
2 2026-02-16 02:00:00          7.1         4.7   0.0            0.0
3 2026-02-16 03:00:00          6.1         5.6   0.0            0.0
4 2026-02-16 04:00:00          4.8         5.2   0.0            0.0

In [19]:
taxi_trips_with_weather = taxi_trips.merge(weather_df, left_on="datetime_for_weather", right_on="datetime")

taxi_trips_with_weather.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,datetime,temperature,wind_speed,rain,precipitation
0,e5d9a80c893b13e39f3fffa499adcea74e19cc38,5e6ba3d77c1e1597624402bd204e81b4acbc3bdb103741...,2026-02-16 23:45:00,2026-02-17T00:00:00.000,960,6.9,76,10,19.25,0,0,4,23.25,Cash,Transit Administrative Center Inc,41.980264315,-87.913624596,41.985015101,-87.804532006,2026-02-16 23:00:00,2026-02-16,2026-02-16 23:00:00,14.6,12.1,0.0,0.0
1,e193c1549807946d6e8715ba43871ac5106bce25,9e00db075b98e6b900e33ebc47977f154cd3aaae5385b1...,2026-02-16 23:45:00,2026-02-17T00:00:00.000,1285,13.51,76,24,34.25,7.95,0,5,47.7,Credit Card,Medallion Leasin,41.980264315,-87.913624596,41.901206994,-87.676355989,2026-02-16 23:00:00,2026-02-16,2026-02-16 23:00:00,14.6,12.1,0.0,0.0
2,def0fc74b9118c81bfcbe39702e253559d705c1b,2a29bcc02d98eb9e748a8427ffd773934047f77e20f703...,2026-02-16 23:45:00,2026-02-17T00:00:00.000,1349,18.12,76,32,44.25,9.95,0,5,59.7,Mobile,City Service,41.980264315,-87.913624596,41.878865584,-87.625192142,2026-02-16 23:00:00,2026-02-16,2026-02-16 23:00:00,14.6,12.1,0.0,0.0
3,deec956f2f84b684b0ecb883b6658ad4b0c49a1f,fb1ed566274f6a66dfcddbe4c014bbe87ac3516412dfe6...,2026-02-16 23:45:00,2026-02-17T00:00:00.000,397,1.26,8,32,7.78,0,0,0,8.28,Mobile,Sun Taxi,41.899602111,-87.633308037,41.878865584,-87.625192142,2026-02-16 23:00:00,2026-02-16,2026-02-16 23:00:00,14.6,12.1,0.0,0.0
4,d5d062aca95ab6b6101a19d75630a090318f1907,a6339ac0faf854f037370b311945d5e1e67b8fd7ff537d...,2026-02-16 23:45:00,2026-02-17T00:15:00.000,1514,21.62,76,59,75,0,0,0,75,Cash,City Service,41.980264315,-87.913624596,41.829922304,-87.672502646,2026-02-16 23:00:00,2026-02-16,2026-02-16 23:00:00,14.6,12.1,0.0,0.0

### Transformation: data type conversions

In [20]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 10661 entries, 0 to 12116
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     10661 non-null  str
 1   taxi_id                     10661 non-null  str
 2   trip_start_timestamp        10661 non-null  datetime64[us]
 3   trip_end_timestamp          10661 non-null  str
 4   trip_seconds                10661 non-null  str
 5   trip_miles                  10661 non-null  str
 6   pickup_community_area_id    10661 non-null  str
 7   dropoff_community_area_id   10661 non-null  str
 8   fare                        10661 non-null  str
 9   tips                        10661 non-null  str
 10  tolls                       10661 non-null  str
 11  extras                      10661 non-null  str
 12  trip_total                  10661 non-null  str
 13  payment_type                10661 non-null  str
 14  company                     10661 non-null  str
 15  pickup_centroid_latitude    10661 non-null  str
 16  pickup_centroid_longitude   10661 non-null  str
 17  dropoff_centroid_latitude   10661 non-null  str
 18  dropoff_centroid_longitude  10661 non-null  str
 19  datetime_for_weather        10661 non-null  datetime64[us]
 20  trip_start_date             10661 non-null  object
dtypes: datetime64[us](2), object(1), str(18)
memory usage: 1.8+ MB

In [21]:
taxi_trips_original = taxi_trips.copy()

In [22]:
data_types = {
    "trip_end_timestamp": "datetime64[ns]",
    "trip_seconds": "int32",
    "trip_miles": "float",
    "pickup_community_area_id": "int8",
    "dropoff_community_area_id": "int8",
    "fare": "float",
    "tips": "float",
    "tolls": "float",
    "extras": "float",
    "trip_total": "float",
    "pickup_centroid_latitude": "float",
    "pickup_centroid_longitude": "float",
    "dropoff_centroid_latitude": "float",
    "dropoff_centroid_longitude": "float"
}

taxi_trips = taxi_trips.astype(data_types)

In [23]:
taxi_trips.describe()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
count,10661,10661,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661.000000,10661
mean,2026-02-16 13:59:19.562892,2026-02-16 14:18:03.782009344,1127.622549,6.941449,36.746928,23.985649,22.986967,2.796825,0.007907,1.499666,27.566152,41.905928,-87.709967,41.894269,-87.656682,2026-02-16 13:36:56.865209
min,2026-02-16 00:00:00,2026-02-16 00:00:00,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.660136,-87.913625,41.660136,-87.913625,2026-02-16 00:00:00
25%,2026-02-16 10:30:00,2026-02-16 10:45:00,459.000000,1.190000,8.000000,8.000000,8.010000,0.000000,0.000000,0.000000,9.500000,41.878866,-87.804532,41.878866,-87.663518,2026-02-16 10:00:00
50%,2026-02-16 14:15:00,2026-02-16 14:30:00,839.000000,3.290000,32.000000,24.000000,14.750000,0.000000,0.000000,0.000000,16.750000,41.899602,-87.642808,41.893216,-87.633308,2026-02-16 14:00:00
75%,2026-02-16 17:45:00,2026-02-16 18:15:00,1559.000000,12.760000,76.000000,32.000000,35.250000,5.000000,0.000000,4.000000,45.000000,41.979071,-87.626211,41.922686,-87.625192,2026-02-16 17:00:00
max,2026-02-16 23:45:00,2026-02-17 12:15:00,62976.000000,1122.210000,77.000000,77.000000,5500.000000,40.000000,6.000000,199.990000,5500.000000,42.009623,-87.534903,42.009623,-87.534903,2026-02-16 23:00:00
std,NaN,NaN,1452.595947,12.742164,27.216158,19.786370,61.806521,4.027926,0.175680,3.897151,63.096296,0.064272,0.118950,0.055720,0.063492,NaN

##### Memory usage

In [26]:
orig_mem = taxi_trips_original.memory_usage(deep=True).sum()
opt_mem = taxi_trips.memory_usage(deep=True).sum()

reduction = (orig_mem - opt_mem) / orig_mem * 100

print(f"Original: {orig_mem:,} bytes")
print(f"Optimized: {opt_mem:,} bytes")
print(f"Memory reduces by: {reduction:.2f} %")

Original: 14,695,286 bytes
Optimized: 6,182,897 bytes
Memory reduces by: 57.93 %

#### Sanity checks

In [27]:
taxi_trips[taxi_trips["trip_end_timestamp"] == taxi_trips["trip_end_timestamp"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
1184,9c0b6b37fcc75d87255e4286d05e88feb5eee5b2,a702989206ab84c8c7368a4db8d7b73bee5d39a3f86122...,2026-02-16 20:45:00,2026-02-17 12:15:00,55702,32.92,76,76,78.5,0.0,0.0,8.0,86.5,Cash,Koam Taxi Association,41.979071,-87.90304,41.979071,-87.90304,2026-02-16 20:00:00,2026-02-16

In [28]:
taxi_trips[taxi_trips["trip_seconds"] == taxi_trips["trip_seconds"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
7101,dd5f0876fa01ce59b27ac68e18d90630bc52fc7a,488f74778b200fa256453e785aceb902249139d4880bc1...,2026-02-16 13:00:00,2026-02-17 06:30:00,62976,11.74,76,76,33.75,0.0,0.0,0.0,33.75,Cash,Chicago Taxicab,41.979071,-87.90304,41.979071,-87.90304,2026-02-16 13:00:00,2026-02-16

In [29]:
taxi_trips[taxi_trips["fare"] == taxi_trips["fare"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
4542,f78c37aa8a7aff5cdb16763f698758873ac4f8fc,f19b6b38529c21e161c145c467760a5897eb378f4a8d75...,2026-02-16 16:00:00,2026-02-16 16:00:00,201,0.0,35,35,5500.0,0.0,0.0,0.0,5500.0,Cash,Tac - American United Dispatch,41.835118,-87.618678,41.835118,-87.618678,2026-02-16 16:00:00,2026-02-16

### Creating dimension table for Company and Payment Type

#### Company dimension

In [30]:
dim_company = taxi_trips["company"].drop_duplicates().reset_index(drop=True)

dim_company = pd.DataFrame(

    {
        "company_id": range(1,len(dim_company) + 1),
        "company": dim_company
    }

)

dim_company.tail()

    company_id                         company
26          27         2733 - 74600 Benny Jona
27          28  Tac - American United Dispatch
28          29                       U Taxicab
29          30     3556 - 36214 RC Andrews Cab
30          31      5167 - 71969 5167 Taxi Inc

#### Payment type dimension

In [31]:
dim_payment_type = taxi_trips["payment_type"].drop_duplicates().reset_index(drop=True)

dim_payment_type = pd.DataFrame(

    {
        "payment_type_id": range(1,len(dim_payment_type) + 1),
        "payment_type": dim_payment_type
    }

)

dim_payment_type

   payment_type_id payment_type
0                1         Cash
1                2  Credit Card
2                3       Mobile
3                4      Unknown
4                5       Prcard
5                6    No Charge
6                7      Dispute

### Merging back to the Fact table

In [32]:
fact_taxi_trips = taxi_trips.merge(dim_payment_type, on="payment_type")
fact_taxi_trips = fact_taxi_trips.merge(dim_company, on="company")

In [33]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
7203,609906e92088caf6715b7af6f6bd299dc936b527,d12b9e3cb8201f4c58e7d3ad3a970bb83f46788415f5d9...,2026-02-16 11:45:00,2026-02-16 12:00:00,951,2.99,28,33,12.00,2.5,0.0,0.0,15.00,Credit Card,Medallion Leasin,41.874005,-87.663518,41.857184,-87.620335,2026-02-16 11:00:00,2026-02-16,2,2
4002,324bb33fc7337cb84f4016705d88b846420fc360,29cfaf00459352d74acd44380b6f52f30b5f5586013fd4...,2026-02-16 16:00:00,2026-02-16 16:15:00,660,1.70,32,32,8.50,2.0,0.0,1.0,11.50,Credit Card,Transit Administrative Center Inc,41.878866,-87.625192,41.878866,-87.625192,2026-02-16 16:00:00,2026-02-16,2,1
3585,6ece5ff4eda21a1d1401dad7ee578a6964a53a96,09047645e67e1eb99be35c5c6d94c7a6f4b8ca86448ad4...,2026-02-16 16:30:00,2026-02-16 16:45:00,1720,12.52,3,41,34.75,0.0,0.0,0.0,34.75,Prcard,Taxicab Insurance Agency Llc,41.965812,-87.655879,41.794090,-87.592311,2026-02-16 16:00:00,2026-02-16,5,7
10061,5f245967946b23a14ea59365e1b81a02a55b9e7f,86b07dc8beb256766f2025da2b99b77345074852eabbdf...,2026-02-16 06:30:00,2026-02-16 06:45:00,258,0.93,32,32,7.01,0.0,0.0,0.0,7.51,Mobile,Sun Taxi,41.884987,-87.620993,41.880994,-87.632746,2026-02-16 06:00:00,2026-02-16,3,4
8873,be733c920fdc9e7a94726f62e07b02f815d339d2,f6d1b6c930d62f6d8cbbd8f86a593ff057408c82f76474...,2026-02-16 09:00:00,2026-02-16 09:00:00,252,0.65,28,32,5.25,0.0,0.0,0.0,5.25,Cash,Taxicab Insurance Agency Llc,41.879255,-87.642649,41.880994,-87.632746,2026-02-16 09:00:00,2026-02-16,1,7

In [35]:
fact_taxi_trips.drop(["payment_type","company"], axis = 1, inplace=True)

In [36]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
1344,51a219fa75d6c6d00e61d8a3425d3acbac8d7b7c,f0d6376865e19a2dae04d7d5401649247eb526372356ac...,2026-02-16 20:00:00,2026-02-16 20:15:00,327,0.67,8,8,5.96,0.00,0.0,0.0,6.46,41.899602,-87.633308,41.899602,-87.633308,2026-02-16 20:00:00,2026-02-16,3,7
1225,0b1ee4888a743415383186acf50987d02675385b,8c508a77909d4e965c01698b799c7b25ab31d609051979...,2026-02-16 20:15:00,2026-02-16 20:45:00,1260,9.30,28,3,26.00,5.30,0.0,0.0,31.30,41.874005,-87.663518,41.965812,-87.655879,2026-02-16 20:00:00,2026-02-16,2,9
6107,1071508beb5ee5219ea423f837125c3849e71c99,3d9da170c3265c7027541b4dd1802eb22d897f005fedfa...,2026-02-16 13:15:00,2026-02-16 13:30:00,1080,2.37,3,4,11.00,2.00,0.0,0.0,13.50,41.965812,-87.655879,41.975171,-87.687516,2026-02-16 13:00:00,2026-02-16,2,6
4437,bccdeb5623fd31861626b2ba743f9844d6a38b74,2bcc0530f9df7b00fe6e4ebdc1203664123d7208c90e47...,2026-02-16 15:15:00,2026-02-16 15:45:00,1216,4.12,28,8,15.84,4.01,0.0,0.0,20.35,41.870415,-87.675086,41.902788,-87.626146,2026-02-16 15:00:00,2026-02-16,3,10
9955,c08fadb9dd8bb432ecf9f9d0e7eddc6346c59e6c,f8b1b8a42dc1d80d7e8fa85b7b32b04b2bdda375d4467a...,2026-02-16 06:45:00,2026-02-16 07:15:00,1630,9.12,6,27,27.00,0.00,0.0,0.0,27.00,41.944227,-87.655998,41.878914,-87.705897,2026-02-16 06:00:00,2026-02-16,5,6

In [ ]:
#dim_payment_type.to_csv("dim_payment_type.csv", index=False)
#dim_company.to_csv("dim_company.csv", index=False)