In [2]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

import pandas as pd
pd.set_option("display.max_columns",30)
import requests

In [3]:
current_datetime = datetime.now() - relativedelta(month=2)
formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = (

    f"https://data.cityofchicago.org/resource/ajtu-isnz.json?"
    f"$where=trip_start_timestamp >= '{formatted_datetime}T00:00:00' "
    f"AND trip_start_timestamp <= '{formatted_datetime}T23:59:59' "
    f"&$limit=30000"
)

response = requests.get(url)
data = response.json()

len(data)

16369

In [4]:
taxi_trips = pd.DataFrame(data)

#taxi_trips.head()

In [5]:
taxi_trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 16369 entries, 0 to 16368
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     16369 non-null  str
 1   taxi_id                     16369 non-null  str
 2   trip_start_timestamp        16369 non-null  str
 3   trip_end_timestamp          16368 non-null  str
 4   trip_seconds                16367 non-null  str
 5   trip_miles                  16369 non-null  str
 6   pickup_community_area       15774 non-null  str
 7   fare                        16352 non-null  str
 8   tips                        16352 non-null  str
 9   tolls                       16352 non-null  str
 10  extras                      16352 non-null  str
 11  trip_total                  16352 non-null  str
 12  payment_type                16369 non-null  str
 13  company                     16369 non-null  str
 14  pickup_centroid_latitude    15783 non-null  str
 15  pickup_centroid_longitude   15783 non-null  str
 16  pickup_centroid_location    15783 non-null  object
 17  dropoff_community_area      14883 non-null  str
 18  dropoff_centroid_latitude   14948 non-null  str
 19  dropoff_centroid_longitude  14948 non-null  str
 20  dropoff_centroid_location   14948 non-null  object
 21  pickup_census_tract         7158 non-null   str
 22  dropoff_census_tract        6953 non-null   str
dtypes: object(2), str(21)
memory usage: 2.9+ MB

In [6]:
taxi_trips.describe()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
count,16369,16369,16369,16368,16367,16369,15774,16352,16352,16352,16352,16352,16369,16369,15783,15783,15783,14883,14948,14948,14948,7158,6953
unique,16369,2112,96,105,3085,2261,76,1942,1008,30,185,2897,7,30,141,141,141,77,159,159,159,65,83
top,bd4ee79c3f29356b74d9455548c8fa80cdc00bbb,18cc8f12635a8251621a44661119a9d3c551d47b75a30d...,2026-02-17T17:15:00.000,2026-02-17T09:00:00.000,420,0,76,8.5,0,0,0,3.25,Credit Card,Flash Cab,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",8,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",17031980000,17031839100
freq,1,33,343,361,162,1062,3432,452,8851,16231,11873,243,5803,3592,1784,1784,1784,3986,1495,1495,1495,1648,1348

In [7]:
taxi_trips[taxi_trips["fare"].isna()].sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
4827,c83f166e7c840a8acd319b36dd7a40b86dd0fdc2,34ee7f8a6c324ff6626c55b5485218db9f46b28c5ac7a8...,2026-02-17T17:00:00.000,2026-02-17T17:45:00.000,2736,17.8,8,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.892507781,-87.626214906,"{'type': 'Point', 'coordinates': [-87.62621490...",76,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",17031081500,17031980000
11925,0269635126ce9884e8d2d85298bfeee53d7acd49,f5cbc985c44eccd8aaab230d252a78e7e3e50f71a4909b...,2026-02-17T10:00:00.000,2026-02-17T10:30:00.000,1559,6.73,10,NaN,NaN,NaN,NaN,NaN,Cash,Flash Cab,41.985015101,-87.804532006,"{'type': 'Point', 'coordinates': [-87.80453200...",NaN,NaN,NaN,NaN,NaN,NaN
2342,3830e960ae6129a32dd0487e18137219a10f6f7e,e8b60c43eaaae4c1bad2c23e45e93ad77c1e85d3a2f13d...,2026-02-17T19:30:00.000,2026-02-17T19:45:00.000,893,3.96,76,NaN,NaN,NaN,NaN,NaN,Cash,Sun Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",NaN,NaN,NaN,NaN,NaN,NaN
10812,14b96748f2edfb6a7b8f3916f4f18202752d231a,2407ff99e367ceb469a8cc6663e6ad6ec51fb0f401d370...,2026-02-17T11:15:00.000,2026-02-17T11:45:00.000,1732,17.93,76,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",8,41.890922026,-87.618868355,"{'type': 'Point', 'coordinates': [-87.61886835...",17031980000,17031081403
14180,6c4f651f0c6bf364b6cac16efff6633f96e67833,0044e6c0d091476299b99345501f756b23632a96cbaf40...,2026-02-17T08:15:00.000,2026-02-17T08:15:00.000,NaN,0,33,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.849246754,-87.624135298,"{'type': 'Point', 'coordinates': [-87.62413529...",33,41.849246754,-87.624135298,"{'type': 'Point', 'coordinates': [-87.62413529...",17031841000,17031841000

### Transformaion: deal with NaN values

In [8]:
taxi_trips.drop(["pickup_census_tract","dropoff_census_tract"],axis=1,inplace=True)

taxi_trips.drop(["pickup_centroid_location","dropoff_centroid_location"],axis=1,inplace=True)

In [9]:
taxi_trips.dropna(inplace=True)

In [10]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 14688 entries, 3 to 16368
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     14688 non-null  str
 1   taxi_id                     14688 non-null  str
 2   trip_start_timestamp        14688 non-null  str
 3   trip_end_timestamp          14688 non-null  str
 4   trip_seconds                14688 non-null  str
 5   trip_miles                  14688 non-null  str
 6   pickup_community_area       14688 non-null  str
 7   fare                        14688 non-null  str
 8   tips                        14688 non-null  str
 9   tolls                       14688 non-null  str
 10  extras                      14688 non-null  str
 11  trip_total                  14688 non-null  str
 12  payment_type                14688 non-null  str
 13  company                     14688 non-null  str
 14  pickup_centroid_latitude    14688 non-null  str
 15  pickup_centroid_longitude   14688 non-null  str
 16  dropoff_community_area      14688 non-null  str
 17  dropoff_centroid_latitude   14688 non-null  str
 18  dropoff_centroid_longitude  14688 non-null  str
dtypes: str(19)
memory usage: 2.2 MB

### Transformation: renaming

In [11]:
taxi_trips.rename(columns= { "pickup_community_area" : "pickup_community_area_id", 
                           "dropoff_community_area" : "dropoff_community_area_id"
                           }, inplace=True)

In [12]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id', 'fare',
       'tips', 'tolls', 'extras', 'trip_total', 'payment_type', 'company',
       'pickup_centroid_latitude', 'pickup_centroid_longitude',
       'dropoff_community_area_id', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude'],
      dtype='str')

### Transformation:create helper column for weather and date dimension

In [13]:
taxi_trips["trip_start_timestamp"] = pd.to_datetime(taxi_trips["trip_start_timestamp"])

In [14]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 14688 entries, 3 to 16368
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     14688 non-null  str
 1   taxi_id                     14688 non-null  str
 2   trip_start_timestamp        14688 non-null  datetime64[us]
 3   trip_end_timestamp          14688 non-null  str
 4   trip_seconds                14688 non-null  str
 5   trip_miles                  14688 non-null  str
 6   pickup_community_area_id    14688 non-null  str
 7   fare                        14688 non-null  str
 8   tips                        14688 non-null  str
 9   tolls                       14688 non-null  str
 10  extras                      14688 non-null  str
 11  trip_total                  14688 non-null  str
 12  payment_type                14688 non-null  str
 13  company                     14688 non-null  str
 14  pickup_centroid_latitude    14688 non-null  str
 15  pickup_centroid_longitude   14688 non-null  str
 16  dropoff_community_area_id   14688 non-null  str
 17  dropoff_centroid_latitude   14688 non-null  str
 18  dropoff_centroid_longitude  14688 non-null  str
dtypes: datetime64[us](1), str(18)
memory usage: 2.2 MB

In [15]:
taxi_trips["datetime_for_weather"] = taxi_trips["trip_start_timestamp"].dt.floor("h")

In [16]:
taxi_trips["datetime_for_weather"].unique()

<DatetimeArray>
['2026-02-17 23:00:00', '2026-02-17 22:00:00', '2026-02-17 21:00:00',
 '2026-02-17 20:00:00', '2026-02-17 19:00:00', '2026-02-17 18:00:00',
 '2026-02-17 17:00:00', '2026-02-17 16:00:00', '2026-02-17 15:00:00',
 '2026-02-17 14:00:00', '2026-02-17 13:00:00', '2026-02-17 12:00:00',
 '2026-02-17 11:00:00', '2026-02-17 10:00:00', '2026-02-17 09:00:00',
 '2026-02-17 08:00:00', '2026-02-17 07:00:00', '2026-02-17 06:00:00',
 '2026-02-17 05:00:00', '2026-02-17 04:00:00', '2026-02-17 03:00:00',
 '2026-02-17 02:00:00', '2026-02-17 01:00:00', '2026-02-17 00:00:00']
Length: 24, dtype: datetime64[us]

In [17]:
taxi_trips["trip_start_date"] = pd.to_datetime(taxi_trips["trip_start_timestamp"]).dt.date

In [18]:
taxi_trips["trip_start_date"].sample(5)

4108     2026-02-17
11577    2026-02-17
756      2026-02-17
7557     2026-02-17
11638    2026-02-17
Name: trip_start_date, dtype: object

 ### check: join taxi and weather data

In [19]:
current_datetime = datetime.now() - relativedelta(month=2)
formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = ("https://archive-api.open-meteo.com/v1/era5")


params = {
    "latitude": 41.85,
    "longitude": -87.65,
    "start_date": formatted_datetime,
    "end_date": formatted_datetime,
    "hourly":"temperature_2m,wind_speed_10m,rain,precipitation"

}

response = requests.get(url, params = params)
data = response.json()

weather_data = {
    "datetime": data["hourly"]["time"],
    "temperature": data["hourly"]["temperature_2m"],
    "wind_speed": data["hourly"]["wind_speed_10m"],
    "rain": data["hourly"]["rain"],
    "precipitation": data["hourly"]["precipitation"],
}

weather_df = pd.DataFrame(weather_data)

weather_df["datetime"] = pd.to_datetime(weather_df["datetime"])

weather_df.head()

             datetime  temperature  wind_speed  rain  precipitation
0 2026-02-17 00:00:00         12.9        11.0   0.0            0.0
1 2026-02-17 01:00:00         12.6        14.2   0.0            0.0
2 2026-02-17 02:00:00         12.1        15.5   0.0            0.0
3 2026-02-17 03:00:00         10.8        15.3   0.0            0.0
4 2026-02-17 04:00:00          9.4        14.7   0.0            0.0

In [20]:
taxi_trips_with_weather = taxi_trips.merge(weather_df, left_on="datetime_for_weather", right_on="datetime")

taxi_trips_with_weather.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,datetime,temperature,wind_speed,rain,precipitation
0,a7b61a599b6718dc5fe2e8cc4eaf9d57f561f13f,ffb8cefb331d92d05289bb6d84fba73aac7ed8252c6f4b...,2026-02-17 23:45:00,2026-02-17T23:45:00.000,4,0,8,60,12.1,0,0,72.6,Credit Card,Flash Cab,41.899602111,-87.633308037,8,41.899602111,-87.633308037,2026-02-17 23:00:00,2026-02-17,2026-02-17 23:00:00,9.2,13.8,0.0,0.0
1,a735ce0954142ee7030e6ced5619f2f5b9645db1,805857b679797dfe185017d79e00742e3f1a6e46f2ad28...,2026-02-17 23:45:00,2026-02-17T23:45:00.000,5,0,8,72.5,10.95,0,0,83.95,Credit Card,5 Star Taxi,41.899602111,-87.633308037,8,41.899602111,-87.633308037,2026-02-17 23:00:00,2026-02-17,2026-02-17 23:00:00,9.2,13.8,0.0,0.0
2,a43b47eb4522a47d641e287792ce954ad763e7ae,96c3fa383c9adacc965af778248d6ef1b3a20ada7e623e...,2026-02-17 23:45:00,2026-02-18T00:15:00.000,1668,13.94,76,36,0,0,7,43,Cash,Flash Cab,41.980264315,-87.913624596,6,41.944226601,-87.655998182,2026-02-17 23:00:00,2026-02-17,2026-02-17 23:00:00,9.2,13.8,0.0,0.0
3,a2cd354b4166d6c7041bcc2a1907d2762621f74d,da23cb9383e3ce659712920d1633a3d73b24f85ccf7d52...,2026-02-17 23:45:00,2026-02-18T00:15:00.000,1425,14.05,76,35.75,0,0,4,39.75,Cash,Sun Taxi,41.980264315,-87.913624596,6,41.944226601,-87.655998182,2026-02-17 23:00:00,2026-02-17,2026-02-17 23:00:00,9.2,13.8,0.0,0.0
4,a010f4e23eb2af9a236e2170562ed5c0d4b3ff99,16c9cec3bf7e9c7a75a8c64e649e390af508e6e9694b80...,2026-02-17 23:45:00,2026-02-17T23:45:00.000,600,4.9,8,15,0,0,0,15,Cash,Transit Administrative Center Inc,41.899602111,-87.633308037,3,41.96581197,-87.655878786,2026-02-17 23:00:00,2026-02-17,2026-02-17 23:00:00,9.2,13.8,0.0,0.0

### Transformation: data type conversions

In [21]:
taxi_trips.info()

<class 'pandas.DataFrame'>
Index: 14688 entries, 3 to 16368
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     14688 non-null  str
 1   taxi_id                     14688 non-null  str
 2   trip_start_timestamp        14688 non-null  datetime64[us]
 3   trip_end_timestamp          14688 non-null  str
 4   trip_seconds                14688 non-null  str
 5   trip_miles                  14688 non-null  str
 6   pickup_community_area_id    14688 non-null  str
 7   fare                        14688 non-null  str
 8   tips                        14688 non-null  str
 9   tolls                       14688 non-null  str
 10  extras                      14688 non-null  str
 11  trip_total                  14688 non-null  str
 12  payment_type                14688 non-null  str
 13  company                     14688 non-null  str
 14  pickup_centroid_latitude    14688 non-null  str
 15  pickup_centroid_longitude   14688 non-null  str
 16  dropoff_community_area_id   14688 non-null  str
 17  dropoff_centroid_latitude   14688 non-null  str
 18  dropoff_centroid_longitude  14688 non-null  str
 19  datetime_for_weather        14688 non-null  datetime64[us]
 20  trip_start_date             14688 non-null  object
dtypes: datetime64[us](2), object(1), str(18)
memory usage: 2.5+ MB

In [22]:
taxi_trips_original = taxi_trips.copy()

In [23]:
data_types = {
    "trip_end_timestamp": "datetime64[ns]",
    "trip_seconds": "int32",
    "trip_miles": "float",
    "pickup_community_area_id": "int8",
    "dropoff_community_area_id": "int8",
    "fare": "float",
    "tips": "float",
    "tolls": "float",
    "extras": "float",
    "trip_total": "float",
    "pickup_centroid_latitude": "float",
    "pickup_centroid_longitude": "float",
    "dropoff_centroid_latitude": "float",
    "dropoff_centroid_longitude": "float"
}

taxi_trips = taxi_trips.astype(data_types)

In [24]:
taxi_trips.describe()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
count,14688,14688,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688.000000,14688
mean,2026-02-17 13:47:09.718137,2026-02-17 14:04:36.409313792,1047.163603,5.824803,33.705338,19.828263,2.428491,0.004964,1.160976,23.703738,41.900915,-87.691944,24.456223,41.891914,-87.652419,2026-02-17 13:24:35.490196
min,2026-02-17 00:00:00,2026-02-17 00:00:00,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.660136,-87.913625,1.000000,41.660136,-87.913625,2026-02-17 00:00:00
25%,2026-02-17 09:45:00,2026-02-17 10:00:00,438.000000,1.020000,8.000000,7.500000,0.000000,0.000000,0.000000,9.000000,41.878866,-87.687516,8.000000,41.878866,-87.656157,2026-02-17 09:00:00
50%,2026-02-17 13:45:00,2026-02-17 14:15:00,754.000000,2.180000,32.000000,11.460000,0.000000,0.000000,0.000000,13.525000,41.892508,-87.640698,28.000000,41.890922,-87.633308,2026-02-17 13:00:00
75%,2026-02-17 17:45:00,2026-02-17 18:00:00,1449.250000,10.940000,49.000000,31.022500,3.110000,0.000000,0.000000,34.500000,41.944227,-87.625192,32.000000,41.901207,-87.625192,2026-02-17 17:00:00
max,2026-02-17 23:45:00,2026-02-18 09:30:00,56618.000000,55.200000,77.000000,2000.000000,45.000000,6.000000,84.000000,2000.000000,42.009623,-87.534903,77.000000,42.015934,-87.534903,2026-02-17 23:00:00
std,NaN,NaN,1111.877619,6.444937,25.056832,28.318561,3.661446,0.145883,3.407070,30.551476,0.059036,0.107486,18.619617,0.050997,0.058147,NaN

##### Memory usage

In [25]:
orig_mem = taxi_trips_original.memory_usage(deep=True).sum()
opt_mem = taxi_trips.memory_usage(deep=True).sum()

reduction = (orig_mem - opt_mem) / orig_mem * 100

print(f"Original: {orig_mem:,} bytes")
print(f"Optimized: {opt_mem:,} bytes")
print(f"Memory reduces by: {reduction:.2f} %")

Original: 20,240,059 bytes
Optimized: 8,515,257 bytes
Memory reduces by: 57.93 %

#### Sanity checks

In [26]:
taxi_trips[taxi_trips["trip_end_timestamp"] == taxi_trips["trip_end_timestamp"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
2345,36910960260063eed1c3a72016a02b16887b8dd1,3ec761bcbdf1b66135e7f4bf23e1b100d6e4f933e32a76...,2026-02-17 19:30:00,2026-02-18 09:30:00,50207,0.0,35,5.0,0.0,0.0,0.0,5.0,Cash,Tac - Yellow Cab Association,41.835118,-87.618678,32,41.878866,-87.625192,2026-02-17 19:00:00,2026-02-17

In [27]:
taxi_trips[taxi_trips["trip_seconds"] == taxi_trips["trip_seconds"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
16366,5766896fd656c20463894408d086a353ad93c2a4,1d68f4a1c3b620f920838643bf3801e757b6791f86700a...,2026-02-17,2026-02-17 15:45:00,56618,41.83,76,154.5,0.0,0.0,0.0,154.5,Cash,Sun Taxi,41.980264,-87.913625,12,41.99393,-87.758354,2026-02-17,2026-02-17

In [28]:
taxi_trips[taxi_trips["fare"] == taxi_trips["fare"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
15259,ff8d50bdde0f68990d9987e0e9a9b6068194dc29,f19b6b38529c21e161c145c467760a5897eb378f4a8d75...,2026-02-17 07:00:00,2026-02-17 07:15:00,782,0.0,39,2000.0,0.0,0.0,0.0,2000.0,Cash,Tac - American United Dispatch,41.808916,-87.596183,32,41.878866,-87.625192,2026-02-17 07:00:00,2026-02-17

### Creating dimension table for Company and Payment Type

#### Company dimension

In [29]:
dim_company = taxi_trips["company"].drop_duplicates().reset_index(drop=True)

dim_company = pd.DataFrame(

    {
        "company_id": range(1,len(dim_company) + 1),
        "company": dim_company
    }

)

dim_company.tail()

    company_id                      company
25          26      2733 - 74600 Benny Jona
26          27   5167 - 71969 5167 Taxi Inc
27          28       Tac - Yellow Non Color
28          29                    U Taxicab
29          30  3556 - 36214 RC Andrews Cab

#### Payment type dimension

In [30]:
dim_payment_type = taxi_trips["payment_type"].drop_duplicates().reset_index(drop=True)

dim_payment_type = pd.DataFrame(

    {
        "payment_type_id": range(1,len(dim_payment_type) + 1),
        "payment_type": dim_payment_type
    }

)

dim_payment_type

   payment_type_id payment_type
0                1  Credit Card
1                2         Cash
2                3    No Charge
3                4       Mobile
4                5       Prcard
5                6      Unknown
6                7      Dispute

#### Merging back to the Fact table

In [31]:
fact_taxi_trips = taxi_trips.merge(dim_payment_type, on="payment_type")
fact_taxi_trips = fact_taxi_trips.merge(dim_company, on="company")

In [32]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
7493,4f6e3ec98fd082fead96a3e2580f2418e08da46f,1a03c9e2ee0ada917261eaa90da3405be60ee5fb476641...,2026-02-17 13:45:00,2026-02-17 14:15:00,1899,17.06,76,43.00,12.50,0.0,19.0,75.00,Credit Card,Chicago Independents,41.979071,-87.903040,8,41.895033,-87.619711,2026-02-17 13:00:00,2026-02-17,1,5
14,6b80404abca315790382a07ff05d1ac81ce5bb99,6fd459ffaac2670ce6a096faf040b54b265ba8e619befa...,2026-02-17 23:45:00,2026-02-18 00:15:00,1280,17.17,76,42.00,6.98,0.0,4.0,53.48,Credit Card,Blue Ribbon Taxi Association,41.980264,-87.913625,8,41.899602,-87.633308,2026-02-17 23:00:00,2026-02-17,1,6
3637,2106684defef5daf0ba972b9d5b3c9212cb6f021,4e902eb187e3942c1da821c8aa349fc848c6ff3f71f107...,2026-02-17 17:45:00,2026-02-17 18:45:00,3267,17.59,76,44.75,7.54,0.0,5.0,57.79,Credit Card,5 Star Taxi,41.979071,-87.903040,8,41.892042,-87.631864,2026-02-17 17:00:00,2026-02-17,1,2
2426,92cbb04f39a7d6ce9e28b3ba45fafd0a200970e5,ad3406bedb9f10f12fbb5e1f1f7236e883379fd7b58c64...,2026-02-17 19:00:00,2026-02-17 19:15:00,451,1.39,32,7.00,1.88,0.0,0.0,9.38,Mobile,Flash Cab,41.878866,-87.625192,24,41.901207,-87.676356,2026-02-17 19:00:00,2026-02-17,4,1
2018,5c993d4b8ba4055e82462c49463d9b50a9fd97ea,8e343c320df2e6ab0a8aa873e207a6a1ea0a70c0b388c3...,2026-02-17 19:30:00,2026-02-17 20:15:00,2236,18.37,76,45.75,5.12,0.0,5.0,56.37,Mobile,Sun Taxi,41.979071,-87.903040,33,41.859350,-87.617358,2026-02-17 19:00:00,2026-02-17,4,3

In [33]:
fact_taxi_trips.drop(["payment_type","company"], axis = 1, inplace=True)

In [34]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area_id,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
5765,235d22c9e2a6e41e31074e586a441a6deb636e77,00c152d49563ae56e208fde25f6c65b08511d0f50259d1...,2026-02-17 15:45:00,2026-02-17 16:30:00,2791,18.22,76,45.25,9.95,0.0,4.0,59.70,41.979071,-87.903040,32,41.884987,-87.620993,2026-02-17 15:00:00,2026-02-17,1,13
2243,74e90f4b4dbd49d2983fafdcd9143057cd377cea,a33e818f102d2dc8ba6ec21c582cf1aa1cd034a85db091...,2026-02-17 19:15:00,2026-02-17 19:45:00,2023,12.12,76,33.00,9.38,0.0,4.0,46.88,41.980264,-87.913625,4,41.975171,-87.687516,2026-02-17 19:00:00,2026-02-17,1,3
5331,e3fe446fd41e5e4f16c77e2474b568ecf90db9d8,692320c13d5f7819864fb57797a53cd467452176b95411...,2026-02-17 16:00:00,2026-02-17 16:45:00,2845,17.58,76,44.50,9.80,0.0,4.0,58.80,41.979071,-87.903040,32,41.880994,-87.632746,2026-02-17 16:00:00,2026-02-17,1,1
11663,2c17e5b6c31c30c4e323f6d7ece22a20166733db,3b27b62287e6ccacdc2be399cf52fa545d3f063743b016...,2026-02-17 09:15:00,2026-02-17 09:15:00,580,3.90,7,12.76,3.29,0.0,0.0,16.55,41.922686,-87.649489,8,41.899602,-87.633308,2026-02-17 09:00:00,2026-02-17,4,13
8607,40af069833366fb8a2621f801dbc739f00fa3838,a63ecb1af39b43b49c041529edf9352a363e8732107cae...,2026-02-17 12:30:00,2026-02-17 13:00:00,1848,16.93,76,42.50,10.00,0.0,4.0,57.00,41.979071,-87.903040,7,41.916473,-87.641184,2026-02-17 12:00:00,2026-02-17,1,3

In [35]:
#dim_payment_type.to_csv("dim_payment_type.csv", index=False)
#dim_company.to_csv("dim_company.csv", index=False)

#### Create update logic for the dimension tables

In [44]:
dim_payment_type = taxi_trips["payment_type"].drop_duplicates().reset_index(drop=True)

dim_payment_type = pd.DataFrame(

    {
        "payment_type_id": range(1,len(dim_payment_type) + 1),
        "payment_type": dim_payment_type
    }

)

dummy_payment_type_data = [
    {"payment_type":"Credit Card"},
    {"payment_type":"X"},
    {"payment_type":"Y"},
    {"payment_type":"X"},
    
]

dummy_payment_type_data_df = pd.DataFrame(dummy_payment_type_data)

todays_payment_types = pd.DataFrame(dummy_payment_type_data_df["payment_type"].unique(), columns=["payment_type"])
new_payment_types = todays_payment_types[~todays_payment_types["payment_type"].isin(dim_payment_type["payment_type"])]

if not new_payment_types.empty:
    max_id = dim_payment_type["payment_type_id"].max()
    new_payment_types["payment_type_id"] = range(max_id + 1, max_id +1 + len(new_payment_types))
    dim_payment_type = pd.concat([dim_payment_type, new_payment_types], ignore_index=True)

dim_payment_type

   payment_type_id payment_type
0                1  Credit Card
1                2         Cash
2                3    No Charge
3                4       Mobile
4                5       Prcard
5                6      Unknown
6                7      Dispute
7                8            X
8                9            Y

In [46]:
# Testing the logic with different data

dummy_payment_type_data = [
    {"payment_type":"Credit Card"},
    {"payment_type":"X"},
    {"payment_type":"Z"},
    {"payment_type":"Z"},
    
]

dummy_payment_type_data_df = pd.DataFrame(dummy_payment_type_data)

todays_payment_types = pd.DataFrame(dummy_payment_type_data_df["payment_type"].unique(), columns=["payment_type"])
new_payment_types = todays_payment_types[~todays_payment_types["payment_type"].isin(dim_payment_type["payment_type"])]

if not new_payment_types.empty:
    max_id = dim_payment_type["payment_type_id"].max()
    new_payment_types["payment_type_id"] = range(max_id + 1, max_id +1 + len(new_payment_types))
    dim_payment_type = pd.concat([dim_payment_type, new_payment_types], ignore_index=True)

dim_payment_type

   payment_type_id payment_type
0                1  Credit Card
1                2         Cash
2                3    No Charge
3                4       Mobile
4                5       Prcard
5                6      Unknown
6                7      Dispute
7                8            X
8                9            Y
9               10            Z

In [47]:
dim_company.tail()

    company_id                      company
25          26      2733 - 74600 Benny Jona
26          27   5167 - 71969 5167 Taxi Inc
27          28       Tac - Yellow Non Color
28          29                    U Taxicab
29          30  3556 - 36214 RC Andrews Cab

In [52]:
dim_company = taxi_trips["company"].drop_duplicates().reset_index(drop=True)

dim_company = pd.DataFrame(

    {
        "company_id": range(1,len(dim_company) + 1),
        "company": dim_company
    }

)

dummy_company_data = [
    {"company":"Tac - Yellow Non Color"},
    {"company":"TBC - Black Non Color"},
    {"company":"TBC - Blue Non Color"},
    {"company":"TBC - Blue Non Color"},
    
]

dummy_company_data_df = pd.DataFrame(dummy_company_data)

todays_companies = pd.DataFrame(dummy_company_data_df["company"].unique(), columns=["company"])
new_companies = todays_companies[~todays_companies["company"].isin(dim_company["company"])]

if not new_companies.empty:
    max_id = dim_company["company_id"].max()
    new_companies["company_id"] = range(max_id + 1, max_id +1 + len(new_companies))
    dim_company = pd.concat([dim_company, new_companies], ignore_index=True)

dim_company.tail()

    company_id                      company
27          28       Tac - Yellow Non Color
28          29                    U Taxicab
29          30  3556 - 36214 RC Andrews Cab
30          31        TBC - Black Non Color
31          32         TBC - Blue Non Color